### ISSUE TITLE
Error "module 'platform' has no attribute 'linux_distribution'" 

### ISSUE THREAD

**Issue by thecodingfrog** [rafaelzimmermann/cryptowatcher#4]
I get this error : "module 'platform' has no attribute 'linux_distribution'" when running the docker-compose on my armbian.
Tried several things but without luck

**Comment by rafaelzimmermann** [comment]
I am sorry getting this long to reply. I am waiting for my raspberry to arrive so I can test it, I will keep you posted.

**Comment by thecodingfrog** [comment]
ok thank you

**Comment by rafaelzimmermann** [comment]
Can you please check if the latest change fix the issue for you?

f344b7111c41667510ee1f4e1565ee2acb2c0b14

Remember to delete the old image before trying it out.

Thanks!!

**Comment by thecodingfrog** [comment]
Hi, now it works but I've switched to my own grafana/php/mysql homemade solution
